name: Get Son Heung-min Goals

on:
    schedule:
        - cron: "0 */6 * * *" # 6시간마다 한 번씩 자동으로 워크플로우 실행
    workflow_dispatch: {} # 수동으로 워크플로우 트리거

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4 # 버전을 v4로 업데이트
              with:
                  node-version: "20" # 최신 버전 20 사용

            - name: Install required system dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y \
                  libnss3 \
                  libatk1.0-0 \
                  libatk-bridge2.0-0 \
                  libcups2 \
                  libdrm2 \
                  libxkbcommon0 \
                  libxcomposite1 \
                  libxdamage1 \
                  libxrandr2 \
                  libgbm1 \
                  libasound2 \
                  libpangocairo-1.0-0 \
                  libgtk-3-0

            - name: Install Node.js dependencies
              run: npm install

            - name: Run getGoals script
              run: npm start

            - name: List files for debugging
              run: ls -alh

            - name: Commit and push changes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.name "eunohhh"
                  git config --global user.email "bdohhhhh@gmail.com"
                  git add goals/goals.json
                  git commit -m "Update goals data" || echo "No changes to commit"
                  git push origin main || echo "No changes to push"