name: Get Son Heung-min Goals

on:
  schedule:
    - cron: "0 0,12 * * *" # 하루에 2번만 실행 (자정과 정오)
  workflow_dispatch: {} # 수동으로 워크플로우 트리거

jobs:
  get-goals:
    runs-on: ubuntu-22.04
    timeout-minutes: 10 # 타임아웃 설정

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # npm 캐시 사용으로 설치 속도 향상

      - name: Install dependencies
        run: npm ci # npm install 대신 npm ci 사용 (더 빠르고 안정적)

      - name: Run getGoals script with retry
        id: run-script
        run: |
          # 최대 3번 재시도
          for i in {1..3}; do
            echo "Attempt $i of 3"
            if npm start; then
              echo "Script completed successfully"
              echo "success=true" >> $GITHUB_OUTPUT
              break
            else
              echo "Script failed, waiting 60 seconds before retry..."
              sleep 60
            fi
          done

          # 모든 재시도가 실패한 경우
          if [ "${{ steps.run-script.outputs.success }}" != "true" ]; then
            echo "All retry attempts failed"
            exit 1
          fi

      - name: Verify goals data
        run: |
          if [ -f "goals/goals.json" ]; then
            echo "Goals data file exists"
            cat goals/goals.json
            
            # 골 수가 0이 아닌지 확인
            goals=$(jq -r '.goals' goals/goals.json)
            if [ "$goals" = "0" ] || [ "$goals" = "" ]; then
              echo "Warning: Goals count is 0 or empty"
            else
              echo "Goals count: $goals"
            fi
          else
            echo "Goals data file not found"
            exit 1
          fi

      - name: Commit and push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "eunohhh"
          git config --global user.email "bdohhhhh@gmail.com"
          git add goals/goals.json
          git commit -m "Update Son Heung-min goals data - $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Handle failure
        if: failure()
        run: |
          echo "Workflow failed. Check the logs for details."
          echo "Current time: $(date -u)"
          echo "Repository: ${{ github.repository }}"
